### ISSUE TITLE
 The data is not deleted from the directory

### ISSUE THREAD

**Issue by jontofront** [chomupashchuk/delete-file-home-assistant#10]
Hi,
maybe can you check, please where is the problem?
I have motion photos in the www/images/camera folder 

Install service:
![delete](https://user-images.githubusercontent.com/37038426/105019370-b117ad80-5a4e-11eb-837d-52b0217ccfad.jpg)

config in configuration.yaml
`
delete:
  service: delete.files_in_folder
  data:
    folder: "/config/www/images/camera/"
    time: 28800
    only_extensions:
      - ".jpg"
`

But after 'time' in config photos doesn't delete from the folder

Where there is the problem can be?

**Comment by chomupashchuk** [comment]
Note that integration checks exact ending of file name, meaning "jpg" is not the same as "jpeg" or "JPG".
I usually use test folder with copied or created files with short time setting (1-5 seconds) for a quick tests. Can't say for sure what is the case here.

Do you see any events in the logs for the integration? - probably can only detect if folder path is correct

**Comment by jontofront** [comment]
in main conf set  logger to default: warn

I check the error log there are only these:
_2021-01-19 13:35:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for delete which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant._

also, check the file extension:
![Screenshot_4](https://user-images.githubusercontent.com/37038426/105029983-c47d4580-5a5b-11eb-84f3-d5526f09358a.jpg)

config:
![Screenshot_5](https://user-images.githubusercontent.com/37038426/105030154-102fef00-5a5c-11eb-86ba-0ab6bbcdba22.jpg)

file path 
![Screenshot_6](https://user-images.githubusercontent.com/37038426/105030301-453c4180-5a5c-11eb-9142-52007d50aa18.jpg)

:(

**Comment by chomupashchuk** [comment]
I'll try to reproduce it after work.

P.S. It is strange to see how folders are represented, as if "images/camera" is a folder name.

**Comment by chomupashchuk** [comment]
![Capture](https://user-images.githubusercontent.com/50545689/105041019-2c875800-5a6b-11eb-9be6-5ad8c8f05784.PNG)
I have tested and it works for me. Files older than 100 seconds and only with ".jpg" extension.

I have Docker container with volume mounted to "/config" folder, but this should not matter too much I guess vs HASSIO.
The only suspicion is permissions of the folder and files that prevent user from removing files, so maybe try tweaking permissions.

**Comment by jontofront** [comment]
I go error when I cal it in developer tools :(
![image](https://user-images.githubusercontent.com/37038426/105075265-32dcfa80-5a92-11eb-85ff-903d40d8157d.png)

permission is:
![image](https://user-images.githubusercontent.com/37038426/105076024-39b83d00-5a93-11eb-85fa-3cdd93b62e77.png)

**Comment by jontofront** [comment]
change the permission it the same
![image](https://user-images.githubusercontent.com/37038426/105079457-1fcd2900-5a98-11eb-8507-2be80fbf99a5.png)

So it can be because images there are in container

delete intall in this directory it's ok?
![image](https://user-images.githubusercontent.com/37038426/105079843-b0a40480-5a98-11eb-8b0a-d43b1f0f836e.png)

**Comment by chomupashchuk** [comment]
why is service data written that way on your screenshot? You may see format in screenshot I have provided.

**Comment by chomupashchuk** [comment]
Note that `delete` is included in `configuration.yaml` to enable custom component. Service names are `delete.file` or `delete.files_in_folder`. `Data` should only include described data, it should not have service name or word `delete`. You may see examples in `README.MD`

**Comment by jontofront** [comment]
Thanks, it works
![image](https://user-images.githubusercontent.com/37038426/105095558-7cd3d980-5aae-11eb-9841-5af66f5d75aa.png)

Sorry I am not dev my mistake, I use the bad template:
![image](https://user-images.githubusercontent.com/37038426/105095648-a2f97980-5aae-11eb-83ec-376fb119dabb.png)

Thanks very much
