### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'delete'

### ISSUE THREAD

**Issue by ruimarinho** [chomupashchuk/delete-file-home-assistant#12]
Hi,

Newer versions of HASS started reporting this warning. Could you please add the version to `manifest.json`?

Thanks!

**Comment by chomupashchuk** [comment]
There was no manifest file.
Not sure why I haven't seen the warning (unless it was ver recent update or not visible in core version (only in HASS)).

**Comment by ruimarinho** [comment]
Thanks! This will be in an upcoming version (March release). Cheers!
