### ISSUE TITLE
Available in HACs

### ISSUE THREAD

**Issue by dannytsang** [chomupashchuk/delete-file-home-assistant#14]
Is it possible to make this available to install via Home Assistant Community? Sorry if it's already there but I couldn't see it in integrations nor Automation sections.

**Comment by chomupashchuk** [comment]
It was requested few times, some description in another integration developed by me:
https://github.com/chomupashchuk/ariston-aqua-remotethermo-home-assistant/issues/13

Shortly it requires some time and attention, it is lower priority on my opinion compared to bugs, and lately I do not have much of free time.

**Comment by chomupashchuk** [comment]
I have changed the structure and added file but I have no HACS nor I plan to install it. So if you use it you may check if it can be added as a custom repository.

**Comment by dannytsang** [comment]
@chomupashchuk unfortunately no dice
![image](https://user-images.githubusercontent.com/567982/111904800-99ee3f80-8a40-11eb-8fa6-9212ea3d1d5a.png)
I'll see if I can dig into the compliance a bit more over the coming weeks and I appreciate your efforts.

**Comment by chomupashchuk** [comment]
From commit to HACS i see 2 errors:
1. https://github.com/home-assistant/brands should include png icons for "delete", which obviously I have not created.
2. there is an error "HACS load check", which I can't understand as there are no more details. One of the ideas is that release is normally is zip and probably it should be described in hacs.json.
Anyway that is what I expected, that there is lack of information, which leads to more time being spent on it.

**Comment by chomupashchuk** [comment]
Please try again

**Comment by dannytsang** [comment]
Popped up in the list without having to add it as a custom repository (pretty cool!):
![image](https://user-images.githubusercontent.com/567982/111918971-7a2a3c00-8a7f-11eb-8045-c5f505b5487a.png)

However, I cant see where it's installed the files to because it's not in custom_components:
![image](https://user-images.githubusercontent.com/567982/111919182-89f65000-8a80-11eb-9812-9e7cc5c6f51e.png)

Another place I looked was /config/www/community where some of the UI integrations go. This was after doing the mandatory restart after installing or updating in HACs.

**Comment by dannytsang** [comment]
Ah here's the log from the installation:
![image](https://user-images.githubusercontent.com/567982/111919297-36d0cd00-8a81-11eb-99c2-66bd9b8ec984.png)

**Comment by chomupashchuk** [comment]
i have updated json file 2 hours and 30 minutes ago and I do not see such an issue (was flag problem) on my local branch. Maybe there are delays in how HACS works, but not sure.

**Comment by dannytsang** [comment]
I have issues in HACs so I don't think my tests are valid. I can't reinstall or uninstall it from HACs and it gives me the error:
`2021-03-22 17:58:20 ERROR (MainThread) [custom_components.hacs] <Integration chomupashchuk/delete-file-home-assistant> Missing domain
2021-03-22 17:58:20 ERROR (MainThread) [custom_components.hacs] Could not uninstall`

so give me a sec whilst I figure this out and I will report back.

**Comment by dannytsang** [comment]
I removed the custom repo and added it back in and as soon as I add the repo I get the same message about missing a manifest.json. Given it's re-adding the repo there shouldn't be a delay in updates. At this point I'm lost as to what the issue is. Any other ideas @chomupashchuk or maybe someone else can try and see if it's a problem on my end. Sorry to be a blocker on this.

> 
> 
> Ah here's the log from the installation:
> ![image](https://user-images.githubusercontent.com/567982/111919297-36d0cd00-8a81-11eb-99c2-66bd9b8ec984.png)

**Comment by FeikoJoosten** [comment]
Should be fixed in https://github.com/chomupashchuk/delete-file-home-assistant/pull/16

**Comment by chomupashchuk** [comment]
PR merged, so try now.

It is strange that action for verification passes even though it is said to make checks as done in HACS, so probably only part of checks is made. I did not install HACS due to no need for me personally, so please let me know if I can close the ticket.

**Comment by FeikoJoosten** [comment]
Pretty sure there’s either a verification missing. And /or a bug in HACS. No worries I’ll relay it through.

**Comment by chomupashchuk** [comment]
does it mean that it works now?

**Comment by FeikoJoosten** [comment]
I mean, it works for me 😛

**Comment by FeikoJoosten** [comment]
I've created an issue on the HACS github. https://github.com/hacs/integration/issues/2002

**Comment by FeikoJoosten** [comment]
@chomupashchuk apparently in the release of 1.6 the hacs.json had [this](https://github.com/chomupashchuk/delete-file-home-assistant/blob/1.6/hacs.json#L3) enabled. Which changes the structure to expect the component directly in a folder. However, the current hacs.json format is correct and resolves the issue.

**Comment by chomupashchuk** [comment]
So apparently HACS checks release and not the source code or there is some mix of things (data was not fully synched between the two). Glad that it works.

**Comment by FeikoJoosten** [comment]
@chomupashchuk you can use hacs to use development builds. Then you can use the latest commit. But preferably it uses releases.

**Comment by dannytsang** [comment]
Got 1.7 and working. Thank you both.

**Comment by benavern** [comment]
Hi,
I have been looking for this integration for a while (been tweeking with automations but it was very sketchy) and think it should be available without having to add the repository in HACS.

Just wanted to let you know that you should add to the "Integration installation" section of the readme how to add it via HACS I'm sure a lot of people just come, read the readme and go away because it doesn look like it is easy to install. The only ways to know it now is by paying attention to that hacks.json file or (like me) looking to the closed issues

By the way, @chomupashchuk  thank you for this integration, it is very helpfull.
