### ISSUE TITLE
Didn't work in 2021.3.4

### ISSUE THREAD

**Issue by laithalsunni** [chomupashchuk/delete-file-home-assistant#15]
I have installed it by downloading the files and with HACS. but the serves dose not show up.

**Comment by chomupashchuk** [comment]
HACS support is being prototyped and I don't know if it works or not as I do not use HACS but followed the guidelines for the support.
 If files were downloaded manually and you have followed the instructions, then it should work.

**Comment by chomupashchuk** [comment]
I have 2021.3.4 and services are visible and working so most likely instructions were not followed.

HACS is in a separate ticket:
https://github.com/chomupashchuk/delete-file-home-assistant/issues/14
