### ISSUE TITLE
manifest file missing

### ISSUE THREAD

**Issue by Murada99** [chomupashchuk/delete-file-home-assistant#17]
Since ths new version Home Assistant 2021.4.1, we get the following in the log file:
No 'version' key in the manifest file for custom integration 'delete'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'delete'

**Comment by chomupashchuk** [comment]
Did you try to use newer version?
Manifest was updated for some time now

**Comment by Murada99** [comment]
Sorry, I didn't see that a new version is available. I did an update and everything works. Thanks for your job.
