### ISSUE TITLE
HA core: core-2021.6.0 delete: integration could not be setup

### ISSUE THREAD

**Issue by J0nnyBr4v0** [chomupashchuk/delete-file-home-assistant#18]
Hi, 

With the new ha core the integration seems not to work anymore.

## System Health

version | core-2021.6.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4595
Installed Version | 1.12.4
Stage | running
Available Repositories | 822
Installed Repositories | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.05.4
docker_version | 19.03.15
disk_total | 38.7 GB
disk_used | 22.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.4.0), Visual Studio Code (3.4.1), Glances (0.12.1), Home Assistant Google Drive Backup (0.104.3), WireGuard (0.5.1), MariaDB (2.3.0), Samba Backup (4.5.0), TasmoAdmin (0.15.0), Tautulli (2.2.3), ZeroTier One (0.11.0), chrony (2.1.0), Duck DNS (1.12.5), Grafana (6.3.5), InfluxDB (4.1.1), Log Viewer (0.11.0), Zigbee2mqtt (1.18.1-1), Node-RED (9.1.3), Nginx Proxy Manager (0.11.0), Samba NAS (9.3.0-nas8), Terminal & SSH (9.1.3), ESPHome (dev) (dev), VLC (0.1.2), Bitwarden (Vaultwarden) (0.11.0), Mosquitto broker (6.0.1), ESPHome (1.18.0), SQLite Web (3.1.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 28
views | 13
mode | storage

</details>

```
Logger: homeassistant.setup
Source: setup.py:172
First occurred: 17:20:37 (1 occurrences)
Last logged: 17:20:37

Setup failed for delete: Integration not found.
```

**Comment by J0nnyBr4v0** [comment]
Updated to the latest version, this fixed the problem. Thanks

**Comment by chomupashchuk** [comment]
Was just writing to ask it

**Comment by J0nnyBr4v0** [comment]
I was a bit to quick with opening an issue, thank you for your great job anyway :)
