### ISSUE TITLE
Feature request: delete old files to meet required folder size

### ISSUE THREAD

**Issue by RomanDidenko** [chomupashchuk/delete-file-home-assistant#19]
Hi, 

It would nice to have the ability to delete old files if folder size exceeds the desired limit but also keep files that not older than X if folder size is under the ultimate limit (otherwise additionally delete oldest files to meet this ultimate limit).
This way it would be possible to maintain folder size and keep the newest files even first folder size limit is exceeded.

Thanks

**Comment by chomupashchuk** [comment]
I'll consider it

**Comment by chomupashchuk** [comment]
You may try version 1.8. A quick test showed that it should work (new attribute `size`, see readme).

**Comment by RomanDidenko** [comment]
You Rock! Thank you, it works very well.
