### ISSUE TITLE
Mandatory key "folder" is missing. @ data['folder']

### ISSUE THREAD

**Issue by arcangel321** [chomupashchuk/delete-file-home-assistant#20]
Great plugin! But getting an error.

Error:
Mandatory key "folder" is missing. @ data['folder']

with config:
id: '1623488393439'
alias: Deurbell delete
description: ''
trigger:
  - platform: time
    at: '02:05:00'
condition: []
action:
  - service: delete.files_in_folder
    data:
      service: delete.files_in_folder
      data:
        folder: /config/www/deurbel/
        time: 0
mode: single

What can be wrong with the config?

**Comment by chomupashchuk** [comment]
input is YAML, which has strict indentation, which is hard to understand from what you have provided. Service call should not be part of trigger, but an action, so I have no idea what is actually described here.
I guess service call in automation should look something as below, when specific action is executed:
```
service: delete.files_in_folder
data:
  folder: /config/www/deurbel/
  time: 0
```

The error indicates incorrect structure used, which is configuration fault.

**Comment by arcangel321** [comment]
Problem solved going into YAML and there as error with double data:
Here is how it worked for me:
![2021-06-12 12_27_00-Window](https://user-images.githubusercontent.com/50084706/121773048-a2ef3880-cb79-11eb-9f0c-5d8c50407d4d.png)
