### ISSUE TITLE
Error "attention with integration"

### ISSUE THREAD

**Issue by Felixlechatt** [chomupashchuk/delete-file-home-assistant#21]
`Cette erreur provient d'une intégration personnalisée

Logger: custom_components.delete
Source: custom_components/delete/__init__.py:56
Integration: Delete (documentation, issues)
First occurred: 19 mars 2022, 19:11:36 (116 occurrences)
Last logged: 19 mars 2022, 19:27:38

Deleted file /config/www/camera/archive/snapshot_CamSalon_18h50_06-02-2022.jpg
Deleted file /media/camera/archive/snapshot_CamSalon_11h40_19-02-2022.jpg
Deleted file /media/camera/archive/snapshot_CamSalon_10h04_19-02-2022.jpg
Deleted file /media/camera/archive/snapshot_CamSalon_11h42_19-02-2022.jpg
Deleted file /media/camera/archive/snapshot_CamSalon_12h19_19-02-2022.jpg`

**Comment by chomupashchuk** [comment]
This is warning indicating which files were deleted. It was my personal choice to log it as a warning (could be changed to info)
