### ISSUE TITLE
[New feature request] Ability to turn off 'Deleted file ..' WARN from log

### ISSUE THREAD

**Issue by majkers** [chomupashchuk/delete-file-home-assistant#22]
Hello,
is it possible to add ability to turn off those log 'Deleted file....." that appear as WARN in HA log via configuration or sth?

**Comment by majkers** [comment]
![image](https://user-images.githubusercontent.com/21099773/178276994-88a27134-0780-49e4-8981-a33b2ea79954.png)

**Comment by chomupashchuk** [comment]
new parameter "no_warn" in new version

**Comment by majkers** [comment]
Thanks
