### ISSUE TITLE
Recursive delete of multiple directories fails

### ISSUE THREAD

**Issue by danruck** [chomupashchuk/delete-file-home-assistant#4]
Attempting to delete more than one directory deep fails with 'directory not empty' error.

**Comment by chomupashchuk** [comment]
can you provide file structure and example of service call?

I do not use cleanup of subfolders in general, I used service once just for test purpose.

**Comment by danruck** [comment]
Thanks for making this available, it's perfect for handling my cheap camera.
It works perfectly with flat files in the root, but one of my cameras creates this:

-Camera
--192.168.1.114_001241774294
---2020-10-08
----01
-----pic

The service call is:

folder: /media/camera
time: 0
scan_subfolders: true
remove_subfolders: true

**Comment by chomupashchuk** [comment]
Removal of subfolders updated
