### ISSUE TITLE
Clear snapshot folder

### ISSUE THREAD

**Issue by pezlin** [chomupashchuk/delete-file-home-assistant#9]
I am trying to remove files in the Hassio snapshot folder located here: _/usr/share/hassio/backup/_ but in the logs I only get _/usr/share/hassio/backup/ is not recognized as a folder_

**Comment by chomupashchuk** [comment]
Please note that service is run from python development environment, not from OS terminal. There is a check in integration to see if python recognizes folder or file within it's environment. It was not written to communicate outside of HA.

**Comment by pezlin** [comment]
Ok, I was hoping that it was possible to do if the folder was included in _allowlist_external_dirs_ in configuration.yaml

**Comment by chomupashchuk** [comment]
As far as I know HA is run within container on Hassio ( I run single container in Docker), so to delete files folder should be mounted to the container to have an access, or write snapshots to /config folder (good under subfolder) as a network drive by means of addons. Other option is to have bash or other script for example to run on Hassio directly.

**Comment by pezlin** [comment]
Do you know how to config where snapshots are stored?

**Comment by chomupashchuk** [comment]
Unfortunately not
